In [79]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [80]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [81]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [82]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [83]:
df.drop(["deck", "embark_town", "alive", "class", "who", "adult_male"], axis=1, inplace=True)

In [84]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [85]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
alone         0
dtype: int64

In [86]:
df["age"]=df["age"].fillna(df["age"].mean())

In [87]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
alone       0
dtype: int64

In [88]:
df.shape

(891, 9)

In [89]:
df = df.dropna(subset=["embarked"])

In [90]:
df.shape

(889, 9)

In [91]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [92]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [93]:
df['sex'] = le.fit_transform(df['sex'])
df["embarked"] = le.fit_transform(df["embarked"])

In [94]:
df = df.astype(int)

In [95]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [96]:
X = df.drop(columns=["survived"])
y = y = df["survived"]

In [97]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [98]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [99]:
y_pred = model.predict(X_test)

In [100]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [101]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [102]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [103]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [104]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [105]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [106]:
X_trained_Scaled = scaler.fit_transform(X_train)
X_test_Scaled = scaler.fit_transform(X_test)

In [107]:
from sklearn.neighbors import KNeighborsClassifier

In [109]:
KNN_model = KNeighborsClassifier(n_neighbors=5)
KNN_model.fit(X_trained_Scaled, y_train)

KNeighborsClassifier()

In [110]:
y_KNN_pred = KNN_model.predict(X_test_Scaled)

In [111]:
accuracy_score(y_test,y_KNN_pred)

0.7752808988764045

In [112]:
confusion_matrix(y_test,y_KNN_pred)

array([[89, 20],
       [20, 49]])

In [ ]:
print(classification_report(y_test,y_KNN_pred))